version: '3.8'

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "2053:2053"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - vpn-network
    depends_on:
      - xui
      - website

  website:
    image: nginx:1.27-alpine
    container_name: terminaus-website
    restart: unless-stopped
    volumes:
      - ./website:/usr/share/nginx/html:ro
    networks:
      - network
    expose:
      - "80"

  xui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: xui-panel
    restart: unless-stopped
    ports:
      - "2053:2053"  # 3X-UI web panel
    volumes:
      - ./3x-ui/db:/etc/x-ui
      - ./3x-ui/cert:/root/cert
      - ./logs/xui:/var/log
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
      - XUI_USERNAME=admin
      - XUI_PASSWORD=admin123
    networks:
      - vpn-network
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun

networks:
  vpn-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  network:
    driver: bridge

volumes:
  xui-data:
    driver: local
  nginx-logs:
    driver: local